version: "3.8"
name: "auth-service"

services:
  postgres:
    image: postgres:16-alpine
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"
    restart: unless-stopped

  redis:
    image: redis:latest
    expose:
      - "6379"
    restart: unless-stopped
