# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x0cuser_service\"\'\n\x16UserInfoByTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\";\n\x10UserInfoResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05roles\x18\x03 \x03(\t2b\n\x04User\x12Z\n\x12GetUserInfoByToken\x12$.user_service.UserInfoByTokenRequest\x1a\x1e.user_service.UserInfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERINFOBYTOKENREQUEST']._serialized_start=28
  _globals['_USERINFOBYTOKENREQUEST']._serialized_end=67
  _globals['_USERINFORESPONSE']._serialized_start=69
  _globals['_USERINFORESPONSE']._serialized_end=128
  _globals['_USER']._serialized_start=130
  _globals['_USER']._serialized_end=228
# @@protoc_insertion_point(module_scope)
